export const IMG = {
  // Logos
  logoFull: "/images/navkar/logo-lockup-white-clear.png",
  logoFullWhite: "/images/navkar/logo-lockup-white-clear.png",
  logoFullTeal: "/images/navkar/logo-lockup-teal-clear.png",
  logoFullTrans: "/images/navkar/logo-full.png",
  logo: "/images/navkar/logo-lockup-teal-clear.png",
  logoTeal: "/images/navkar/logo-lockup-teal-clear.png",
  logoWhite: "/images/navkar/logo-lockup-white-clear.png",
  emblem: "/images/navkar/logo-emblem-clean.png",
  heroMark: "/images/navkar/logo-hero-mark.png",
  navkarEmblem: "/images/navkar/navkar-emblem.png",
  logoLight: "/images/navkar/logo-light.png",
  brochureCover: "/images/navkar/brochure-cover.webp",

  // Hero & Backgrounds
  hero: "/images/navkar/hero-main.webp",
  heroMain: "/images/navkar/hero-main.webp",
  heroPipes: "/images/navkar/hero-pipes.webp",
  heroYard: "/images/navkar/hero-yard.webp",
  heroSeamless: "/images/navkar/hero-seamless.webp",
  heroLoop: "/images/navkar/hero-loop-720.mp4",
  heroPoster: "/images/navkar/hero-poster.webp",

  // Products
  erw: "/images/navkar/erw-pipes.webp",
  erwPipes: "/images/navkar/erw-pipes.webp",
  hollow: "/images/navkar/hollow-sections.webp",
  hollowSections: "/images/navkar/hollow-sections.webp",
  spiral: "/images/navkar/spiral-pipes.webp",
  spiralPipes: "/images/navkar/spiral-pipes.webp",
  productsErw: "/images/navkar/erw-pipes.webp",
  productsHollow: "/images/navkar/hollow-sections.webp",
  pipesStack: "/images/navkar/erw-pipes.webp",
  hydraulic: "/images/navkar/lancing-pipes.webp",
  lancingPipes: "/images/navkar/hydraulic.jpg",
  seamlessPipes: "/images/navkar/hero-seamless.webp",
  msFittings1: "/images/navkar/fittings.webp",
  msFittings2: "/images/navkar/fittings.jpg",
  msFlanges: "/images/navkar/flanges.jpg",

  // Facility & Stock Yards
  facility: "/images/navkar/yard-1.webp",
  yard1: "/images/navkar/yard-1.webp",
  yard2: "/images/navkar/yard-2.webp",
  yard03: "/images/navkar/updates/yard-03-960.webp",
  yard04: "/images/navkar/updates/yard-04-960.webp",
  yard22: "/images/navkar/updates/yard-22-960.webp",
  yardPanoramic: "/images/navkar/hero-yard.webp",
  aboutFacility: "/images/navkar/yard-2.webp",
  shripalShah: "/images/navkar/shripal-shah.webp",
  harshKothari: "/images/navkar/harsh-kothari.webp",

  // Certificate
  cert: "/images/navkar/jindal-certificate.webp",
  jindalCert: "/images/navkar/jindal-certificate.webp",

  // Applications
  cement: "/images/navkar/cement.webp",
  chemical: "/images/navkar/chemical.webp",
  oilgas: "/images/navkar/oilgas.webp",
  refinery: "/images/navkar/refinery.webp",

  // Export Gallery (19 images)
  exportMain: "/images/navkar/export/export-10.webp",
  export: [
    "/images/navkar/export/export-01.webp",
    "/images/navkar/export/export-02.webp",
    "/images/navkar/export/export-03.webp",
    "/images/navkar/export/export-04.webp",
    "/images/navkar/export/export-05.webp",
    "/images/navkar/export/export-06.webp",
    "/images/navkar/export/export-07.webp",
    "/images/navkar/export/export-08.webp",
    "/images/navkar/export/export-09.webp",
    "/images/navkar/export/export-10.webp",
    "/images/navkar/export/export-11.webp",
    "/images/navkar/export/export-12.webp",
    "/images/navkar/export/export-13.webp",
    "/images/navkar/export/export-14.webp",
    "/images/navkar/export/export-15.webp",
    "/images/navkar/export/export-16.webp",
    "/images/navkar/export/export-17.webp",
    "/images/navkar/export/export-18.webp",
    "/images/navkar/export/export-19.webp",
  ],

  // Yard Updates (28 images)
  yardUpdates: [
    "/images/navkar/updates/yard-01-960.webp",
    "/images/navkar/updates/yard-02-960.webp",
    "/images/navkar/updates/yard-03-960.webp",
    "/images/navkar/updates/yard-04-960.webp",
    "/images/navkar/updates/yard-05-960.webp",
    "/images/navkar/updates/yard-06-960.webp",
    "/images/navkar/updates/yard-07-960.webp",
    "/images/navkar/updates/yard-08-960.webp",
    "/images/navkar/updates/yard-09-960.webp",
    "/images/navkar/updates/yard-10-960.webp",
    "/images/navkar/updates/yard-11-960.webp",
    "/images/navkar/updates/yard-12-960.webp",
    "/images/navkar/updates/yard-13-960.webp",
    "/images/navkar/updates/yard-14-960.webp",
    "/images/navkar/updates/yard-15-960.webp",
    "/images/navkar/updates/yard-16-960.webp",
    "/images/navkar/updates/yard-17-960.webp",
    "/images/navkar/updates/yard-18-960.webp",
    "/images/navkar/updates/yard-19-960.webp",
    "/images/navkar/updates/yard-20-960.webp",
    "/images/navkar/updates/yard-21-960.webp",
    "/images/navkar/updates/yard-22-960.webp",
    "/images/navkar/updates/yard-23-960.webp",
    "/images/navkar/updates/yard-24-960.webp",
    "/images/navkar/updates/yard-25-960.webp",
    "/images/navkar/updates/yard-26-960.webp",
    "/images/navkar/updates/yard-27-960.webp",
    "/images/navkar/updates/yard-28-960.webp",
  ],

  // Videos
  yardTour: "/media/yard-tour-clean.mp4",
  heroLoopVideo: "/images/navkar/hero-loop-720.mp4",

  // Documents
  brochure: "/brochure/Navkar-Tubes-Brochure.pdf",
};
